name: Main

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run tests shard ${{ matrix.shard }}/${{ strategy.job-total }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4, 5, 6]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test-shard -- $(node .scripts/get-test-shard.js ${{ matrix.shard }}/${{ strategy.job-total }})

  join-coverage:
    name: Join coverage
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4